In [1]:
import pandas as pd
import duckdb

In [2]:
# Load the historical player box scores.
player_Stats = duckdb.read_parquet("../data/raw/PlayerStats.parquet").df()

In [3]:
player_Stats.head()

,index,firstName,lastName,personId,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,opponentteamName,...,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints,playerteamId,opponentteamId,comment,startingPosition,gameDate
0,0,Josh,Hart,1628404.0,42500405,2026-06-13 20:30:00,New York,Knicks,San Antonio,Spurs,...,3.0,11.0,3.0,1.0,15.0,1.610613e+09,1.610613e+09,None,F,2026-06-13 20:30:00
1,1,OG,Anunoby,1628384.0,42500405,2026-06-13 20:30:00,New York,Knicks,San Antonio,Spurs,...,0.0,8.0,5.0,1.0,2.0,1.610613e+09,1.610613e+09,None,F,2026-06-13 20:30:00
2,2,Jeremy,Sochan,1631110.0,42500405,2026-06-13 20:30:00,New York,Knicks,San Antonio,Spurs,...,0.0,0.0,0.0,0.0,1.0,1.610613e+09,1.610613e+09,None,None,2026-06-13 20:30:00
3,3,Jordan,McLaughlin,1629162.0,42500405,2026-06-13 20:30:00,San Antonio,Spurs,New York,Knicks,...,0.0,0.0,0.0,0.0,0.0,1.610613e+09,1.610613e+09,DNP - Coach's Decision,None,2026-06-13 20:30:00
4,4,Jordan,Clarkson,203903.0,42500405,2026-06-13 20:30:00,New York,Knicks,San Antonio,Spurs,...,1.0,1.0,0.0,0.0,3.0,1.610613e+09,1.610613e+09,None,None,2026-06-13 20:30:00

In [4]:
# Separate the source timestamp into date and time fields.
player_Stats[["game_Date", "game_Time"]] = player_Stats["gameDate"].str.split(" ", expand=True)

In [5]:
# Keep regular-season player games in the transaction window.
query = """
    SELECT * FROM player_Stats
    WHERE game_Date BETWEEN '1976-10-21' AND '2019-04-10'
    AND gameType = 'Regular Season'
    """

In [6]:
select_Games = duckdb.sql(query).df().reset_index()

In [7]:
select_Games.head()

,level_0,index,firstName,lastName,personId,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,...,foulsPersonal,turnovers,plusMinusPoints,playerteamId,opponentteamId,comment,startingPosition,gameDate,game_Date,game_Time
0,0,253345,Malik,Beasley,1627736.0,21801228,2019-04-10 22:30:00,Denver,Nuggets,Minnesota,...,0.0,0.0,-9.0,1.610613e+09,1.610613e+09,None,None,2019-04-10 22:30:00,2019-04-10,22:30:00
1,1,253346,C.J.,Williams,203710.0,21801228,2019-04-10 22:30:00,Minnesota,Timberwolves,Denver,...,2.0,0.0,11.0,1.610613e+09,1.610613e+09,None,None,2019-04-10 22:30:00,2019-04-10,22:30:00
2,2,253347,Mason,Plumlee,203486.0,21801228,2019-04-10 22:30:00,Denver,Nuggets,Minnesota,...,0.0,0.0,-15.0,1.610613e+09,1.610613e+09,None,None,2019-04-10 22:30:00,2019-04-10,22:30:00
3,3,253348,Nikola,Jokic,203999.0,21801228,2019-04-10 22:30:00,Denver,Nuggets,Minnesota,...,4.0,4.0,16.0,1.610613e+09,1.610613e+09,None,C,2019-04-10 22:30:00,2019-04-10,22:30:00
4,4,253349,Cam,Reynolds,1629244.0,21801228,2019-04-10 22:30:00,Minnesota,Timberwolves,Denver,...,3.0,0.0,6.0,1.610613e+09,1.610613e+09,None,None,2019-04-10 22:30:00,2019-04-10,22:30:00

In [8]:
select_Games.tail()

,level_0,index,firstName,lastName,personId,gameId,gameDateTimeEst,playerteamCity,playerteamName,opponentteamCity,...,foulsPersonal,turnovers,plusMinusPoints,playerteamId,opponentteamId,comment,startingPosition,gameDate,game_Date,game_Time
1072810,1072810,1434968,Earl,Monroe,600006.0,27600007,1976-10-21 19:00:00,New York,Knicks,Los Angeles,...,5.0,0.0,0.0,1.610613e+09,1.610613e+09,None,None,1976-10-21 19:00:00,1976-10-21,19:00:00
1072811,1072811,1434969,Kareem,Abdul-Jabbar,76003.0,27600007,1976-10-21 19:00:00,Los Angeles,Lakers,New York,...,4.0,0.0,0.0,1.610613e+09,1.610613e+09,None,None,1976-10-21 19:00:00,1976-10-21,19:00:00
1072812,1072812,1434970,Lonnie,Shelton,78133.0,27600007,1976-10-21 19:00:00,New York,Knicks,Los Angeles,...,1.0,0.0,0.0,1.610613e+09,1.610613e+09,None,None,1976-10-21 19:00:00,1976-10-21,19:00:00
1072813,1072813,1434971,Jim,McMillian,77554.0,27600007,1976-10-21 19:00:00,New York,Knicks,Los Angeles,...,0.0,0.0,0.0,1.610613e+09,1.610613e+09,None,None,1976-10-21 19:00:00,1976-10-21,19:00:00
1072814,1072814,1434972,Luther,Burden,76303.0,27600007,1976-10-21 19:00:00,New York,Knicks,Los Angeles,...,1.0,0.0,0.0,1.610613e+09,1.610613e+09,None,None,1976-10-21 19:00:00,1976-10-21,19:00:00

In [9]:
# Save the filtered player box scores.
select_Games.to_parquet("../data/interim/filtered_Player_Stats.parquet")

In [10]:
# Load the historical team box scores.
team_Stats = pd.read_csv("../data/raw/TeamStatistics.csv")

In [11]:
# Separate team-game timestamps into date and time fields.
team_Stats[["game_Date", "game_Time"]] = team_Stats["gameDate"].str.split(" ", expand=True)

In [12]:
# Keep regular-season team games in the transaction window.
query2 = """
    SELECT * FROM team_Stats
    WHERE game_Date BETWEEN '1976-10-21' AND '2019-04-10'
    AND gameType = 'Regular Season'
    """

In [13]:
select_Team_Games = duckdb.sql(query2).df().reset_index()

In [14]:
select_Team_Games.head()

,index,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,...,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate,game_Date,game_Time
0,0,21801228,2019-04-10 22:30:00,Minnesota,Timberwolves,1610612750,Denver,Nuggets,1610612743,0,...,NaN,NaN,6.0,0.0,NaN,NaN,NaN,2019-04-10 22:30:00,2019-04-10,22:30:00
1,1,21801228,2019-04-10 22:30:00,Denver,Nuggets,1610612743,Minnesota,Timberwolves,1610612750,1,...,NaN,NaN,8.0,1.0,NaN,NaN,NaN,2019-04-10 22:30:00,2019-04-10,22:30:00
2,2,21801229,2019-04-10 22:30:00,Utah,Jazz,1610612762,Los Angeles,Clippers,1610612746,0,...,NaN,NaN,7.0,0.0,11.0,NaN,11.0,2019-04-10 22:30:00,2019-04-10,22:30:00
3,3,21801229,2019-04-10 22:30:00,Los Angeles,Clippers,1610612746,Utah,Jazz,1610612762,1,...,NaN,NaN,6.0,0.0,17.0,NaN,17.0,2019-04-10 22:30:00,2019-04-10,22:30:00
4,4,21801230,2019-04-10 22:30:00,Sacramento,Kings,1610612758,Portland,Trail Blazers,1610612757,0,...,NaN,NaN,8.0,0.0,NaN,NaN,NaN,2019-04-10 22:30:00,2019-04-10,22:30:00

In [15]:
select_Team_Games.tail()

,index,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,...,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate,game_Date,game_Time
93331,93331,27600005,1976-10-21 19:00:00,Buffalo,Braves,1610612746,Milwaukee,Bucks,1610612749,0,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1976-10-21 19:00:00,1976-10-21,19:00:00
93332,93332,27600006,1976-10-21 19:00:00,Houston,Rockets,1610612745,Atlanta,Hawks,1610612737,0,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1976-10-21 19:00:00,1976-10-21,19:00:00
93333,93333,27600006,1976-10-21 19:00:00,Atlanta,Hawks,1610612737,Houston,Rockets,1610612745,1,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1976-10-21 19:00:00,1976-10-21,19:00:00
93334,93334,27600007,1976-10-21 19:00:00,New York,Knicks,1610612752,Los Angeles,Lakers,1610612747,1,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1976-10-21 19:00:00,1976-10-21,19:00:00
93335,93335,27600007,1976-10-21 19:00:00,Los Angeles,Lakers,1610612747,New York,Knicks,1610612752,0,...,NaN,NaN,0.0,0.0,NaN,NaN,NaN,1976-10-21 19:00:00,1976-10-21,19:00:00

In [16]:
# Save the filtered team context.
select_Team_Games.to_parquet("../data/interim/filtered_Team_Stats.parquet")

In [17]:
select_Games["gameType"].value_counts(dropna=False)

gameType
Regular Season    1072815
Name: count, dtype: int64